chore(deps): bump the go-minor group across 1 directory with 4 updates (#79)
* chore(deps): bump the go-minor group across 1 directory with 4 updates

Bumps the go-minor group with 3 updates in the / directory: [github.com/charmbracelet/colorprofile](https://github.com/charmbracelet/colorprofile), [github.com/hashicorp/go-tfe](https://github.com/hashicorp/go-tfe) and [github.com/spf13/cobra](https://github.com/spf13/cobra).


Updates `github.com/charmbracelet/colorprofile` from 0.3.2 to 0.4.1
- [Release notes](https://github.com/charmbracelet/colorprofile/releases)
- [Commits](https://github.com/charmbracelet/colorprofile/compare/v0.3.2...v0.4.1)

Updates `github.com/charmbracelet/x/term` from 0.2.1 to 0.2.2
- [Commits](https://github.com/charmbracelet/x/compare/ansi/v0.2.1...ansi/v0.2.2)

Updates `github.com/hashicorp/go-tfe` from 1.84.0 to 1.97.0
- [Release notes](https://github.com/hashicorp/go-tfe/releases)
- [Changelog](https://github.com/hashicorp/go-tfe/blob/main/CHANGELOG.md)
- [Commits](https://github.com/hashicorp/go-tfe/compare/v1.84.0...1.97.0)

Updates `github.com/spf13/cobra` from 1.9.1 to 1.10.2
- [Release notes](https://github.com/spf13/cobra/releases)
- [Commits](https://github.com/spf13/cobra/compare/v1.9.1...v1.10.2)

---
updated-dependencies:
- dependency-name: github.com/charmbracelet/colorprofile
  dependency-version: 0.4.1
  dependency-type: direct:production
  update-type: version-update:semver-minor
  dependency-group: go-minor
- dependency-name: github.com/charmbracelet/x/term
  dependency-version: 0.2.2
  dependency-type: direct:production
  update-type: version-update:semver-patch
  dependency-group: go-minor
- dependency-name: github.com/hashicorp/go-tfe
  dependency-version: 1.97.0
  dependency-type: direct:production
  update-type: version-update:semver-minor
  dependency-group: go-minor
- dependency-name: github.com/spf13/cobra
  dependency-version: 1.10.2
  dependency-type: direct:production
  update-type: version-update:semver-minor
  dependency-group: go-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

* chore(deps): fix lipgloss installing with incomptable version

The build log errors about charmbracelet/x/cellbuf package. To fix, just
re-update lipgloss with:

```
go get -u github.com/charmbracelet/lipgloss
```

For posterity, the build log failure:

```
Error: ../../../go/pkg/mod/github.com/charmbracelet/x/cellbuf@v0.0.13-0.20250311204145-2c3ea96c31dd/cell.go:195:8: not enough arguments in call to b.Italic
	have ()
	want (bool)
Error: ../../../go/pkg/mod/github.com/charmbracelet/x/cellbuf@v0.0.13-0.20250311204145-2c3ea96c31dd/cell.go:198:10: b.SlowBlink undefined (type ansi.Style has no field or method SlowBlink)
Error: ../../../go/pkg/mod/github.com/charmbracelet/x/cellbuf@v0.0.13-0.20250311204145-2c3ea96c31dd/cell.go:201:8: not enough arguments in call to b.RapidBlink
	have ()
	want (bool)
Error: ../../../go/pkg/mod/github.com/charmbracelet/x/cellbuf@v0.0.13-0.20250311204145-2c3ea96c31dd/cell.go:204:8: not enough arguments in call to b.Reverse
	have ()
	want (bool)
Error: ../../../go/pkg/mod/github.com/charmbracelet/x/cellbuf@v0.0.13-0.20250311204145-2c3ea96c31dd/cell.go:207:8: not enough arguments in call to b.Conceal
	have ()
	want (bool)
Error: ../../../go/pkg/mod/github.com/charmbracelet/x/cellbuf@v0.0.13-0.20250311204145-2c3ea96c31dd/cell.go:210:8: not enough arguments in call to b.Strikethrough
	have ()
	want (bool)
Error: ../../../go/pkg/mod/github.com/charmbracelet/x/cellbuf@v0.0.13-0.20250311204145-2c3ea96c31dd/cell.go:216:8: not enough arguments in call to b.Underline
	have ()
	want (bool)
Error: ../../../go/pkg/mod/github.com/charmbracelet/x/cellbuf@v0.0.13-0.20250311204145-2c3ea96c31dd/cell.go:218:10: b.DoubleUnderline undefined (type ansi.Style has no field or method DoubleUnderline)
Error: ../../../go/pkg/mod/github.com/charmbracelet/x/cellbuf@v0.0.13-0.20250311204145-2c3ea96c31dd/cell.go:220:10: b.CurlyUnderline undefined (type ansi.Style has no field or method CurlyUnderline)
Error: ../../../go/pkg/mod/github.com/charmbracelet/x/cellbuf@v0.0.13-0.20250311204145-2c3ea96c31dd/cell.go:222:10: b.DottedUnderline undefined (type ansi.Style has no field or method DottedUnderline)
Error: ../../../go/pkg/mod/github.com/charmbracelet/x/cellbuf@v0.0.13-0.20250311204145-2c3ea96c31dd/cell.go:222:10: too many errors
make: *** [Makefile:80: build] Error 1
```

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Zhenya Khvan <zhenya@gptzero.me>